// This file is generated by npm run build:icons
  
  export type IconName =
  	| "alfa"
	| "app-store"
	| "apple-pay"
	| "basket-logo"
	| "belcard"
	| "belcard2"
	| "facebook-logo"
	| "google-play"
	| "instagram-logo"
	| "logo"
	| "mc"
	| "mc2"
	| "samsung-pay"
	| "tiktok-logo"
	| "visa-seq"
	| "visa"
	| "visa2"
	| "vk-logo";
  